In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:
#Create Series with targets

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  \
0         0         0         0         1             7   
1         0         0         0         0             7   
2         0         0         0         1             7   
3         1         0         0         0             7   
4         0         0         0         1             7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [ ]:
#Select Inputs

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
data_with_targets.iloc[:,:14]

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         1             7   
3           1         0         0         0             7   
4           0         0         0         1             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         1             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [15]:
data_with_targets.iloc[:,:-1]

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         1             7   
3           1         0         0         0             7   
4           0         0         0         1             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         1             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [ ]:
#Standardize Data

In [17]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4',
                      'Month Values', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Month Values  \
0   -0.577350 -0.092981 -0.314485  0.821365      0.182726   
1   -0.577350 -0.092981 -0.314485 -1.217485      0.182726   
2   -0.577350 -0.092981 -0.314485  0.821365      0.182726   
3    1.732051 -0.092981 -0.314485 -1.217485      0.182726   
4   -0.577350 -0.092981 -0.314485  0.821365      0.182726   
..        ...       ...       ...       ...           ...   
695  1.732051 -0.092981 -0.314485 -1.217485     -0.388293   
696  1.732051 -0.092981 -0.314485 -1.217485     -0.388293   
697  1.732051 -0.092981 -0.314485 -1.217485     -0.388293   
698 -0.577350 -0.092981 -0.314485  0.821365     -0.388293   
699 -0.577350 -0.092981 -0.314485  0.821365     -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [26]:
scaled_inputs.shape

(700, 11)

In [ ]:
#Split Data

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
train_test_split(scaled_inputs, targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month Values  \
 682 -0.577350 -0.092981  3.179797 -1.217485     -0.388293   
 267 -0.577350 -0.092981  3.179797 -1.217485      0.468236   
 377  1.732051 -0.092981 -0.314485 -1.217485     -1.244823   
 656 -0.577350 -0.092981  3.179797 -1.217485     -0.673803   
 98  -0.577350 -0.092981 -0.314485  0.821365      1.610276   
 ..        ...       ...       ...       ...           ...   
 179  1.732051 -0.092981 -0.314485 -1.217485     -0.959313   
 441 -0.577350 -0.092981 -0.314485  0.821365     -0.102784   
 484 -0.577350 -0.092981 -0.314485  0.821365      0.468236   
 552 -0.577350 -0.092981 -0.314485  0.821365      1.324766   
 242 -0.577350 -0.092981 -0.314485  0.821365      0.182726   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 682                1.171843  1.032682        -0.408580          0  0.880469   
 267                0.190942  0.091435         0.532229          1 -0.019280   
 377          

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [30]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [31]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


In [ ]:
#Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
#Train Model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

C:\Users\tdzhu\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
reg.score(x_train,y_train)

0.7875

In [ ]:
#Manual Check

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [38]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
np.sum((model_outputs==y_train))

441

In [40]:
model_outputs.shape[0]

560

In [41]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7875

In [ ]:
#Find Intercept and coeff

In [42]:
# get the intercept (bias) of our model
reg.intercept_

array([-0.16924304])

In [43]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.0674645 ,  0.33437476,  1.55990772,  1.31151248,  0.18510535,
         0.69063727, -0.19799436,  0.32749477, -0.31577027,  0.37190506,
        -0.32452824]])

In [44]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason 1     2.067464
1                 Reason 2     0.334375
2                 Reason 3     1.559908
3                 Reason 4     1.311512
4             Month Values     0.185105
5   Transportation Expense     0.690637
6                      Age    -0.197994
7          Body Mass Index     0.327495
8                Education    -0.315770
9                 Children     0.371905
10                    Pets    -0.324528

In [47]:
summary_table.index = summary_table.index + 1

summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.169243
1                 Reason 1     2.067464
2                 Reason 2     0.334375
3                 Reason 3     1.559908
4                 Reason 4     1.311512
5             Month Values     0.185105
6   Transportation Expense     0.690637
7                      Age    -0.197994
8          Body Mass Index     0.327495
9                Education    -0.315770
10                Children     0.371905
11                    Pets    -0.324528

In [ ]:
#Interpreting Coeffs

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.169243    0.844304
1                 Reason 1     2.067464    7.904755
2                 Reason 2     0.334375    1.397067
3                 Reason 3     1.559908    4.758382
4                 Reason 4     1.311512    3.711783
5             Month Values     0.185105    1.203345
6   Transportation Expense     0.690637    1.994986
7                      Age    -0.197994    0.820374
8          Body Mass Index     0.327495    1.387488
9                Education    -0.315770    0.729227
10                Children     0.371905    1.450495
11                    Pets    -0.324528    0.722868

In [50]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                 Reason 1     2.067464    7.904755
3                 Reason 3     1.559908    4.758382
4                 Reason 4     1.311512    3.711783
6   Transportation Expense     0.690637    1.994986
10                Children     0.371905    1.450495
2                 Reason 2     0.334375    1.397067
8          Body Mass Index     0.327495    1.387488
5             Month Values     0.185105    1.203345
0                Intercept    -0.169243    0.844304
7                      Age    -0.197994    0.820374
9                Education    -0.315770    0.729227
11                    Pets    -0.324528    0.722868

In [ ]:
#Test Model

In [51]:
reg.score(x_test,y_test)

0.7357142857142858

In [52]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.70787875, 0.29212125],
       [0.57240632, 0.42759368],
       [0.39722156, 0.60277844],
       [0.7871614 , 0.2128386 ],
       [0.06706237, 0.93293763],
       [0.31158323, 0.68841677],
       [0.28623871, 0.71376129],
       [0.08098094, 0.91901906],
       [0.7998164 , 0.2001836 ],
       [0.74960402, 0.25039598],
       [0.46775646, 0.53224354],
       [0.1847786 , 0.8152214 ],
       [0.04107863, 0.95892137],
       [0.75155043, 0.24844957],
       [0.23838403, 0.76161597],
       [0.53708693, 0.46291307],
       [0.53372215, 0.46627785],
       [0.52054949, 0.47945051],
       [0.40619764, 0.59380236],
       [0.0276527 , 0.9723473 ],
       [0.70196092, 0.29803908],
       [0.7871614 , 0.2128386 ],
       [0.40618889, 0.59381111],
       [0.40618889, 0.59381111],
       [0.17505998, 0.82494002],
       [0.75415565, 0.24584435],
       [0.48882312, 0.51117688],
       [0.87893898, 0.12106102],
       [0.13105335, 0.86894665],
       [0.7871614 , 0.2128386 ],
       [0.

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
predicted_proba[:,1]

array([0.29212125, 0.42759368, 0.60277844, 0.2128386 , 0.93293763,
       0.68841677, 0.71376129, 0.91901906, 0.2001836 , 0.25039598,
       0.53224354, 0.8152214 , 0.95892137, 0.24844957, 0.76161597,
       0.46291307, 0.46627785, 0.47945051, 0.59380236, 0.9723473 ,
       0.29803908, 0.2128386 , 0.59381111, 0.59381111, 0.82494002,
       0.24584435, 0.51117688, 0.12106102, 0.86894665, 0.2128386 ,
       0.37681869, 0.69448648, 0.71062609, 0.55844467, 0.2128386 ,
       0.56333657, 0.20877953, 0.8091301 , 0.41394319, 0.62997001,
       0.20411867, 0.42443604, 0.22677723, 0.10509155, 0.85761156,
       0.65319241, 0.70555917, 0.29212125, 0.21098334, 0.19566718,
       0.56875038, 0.0792448 , 0.68841677, 0.26856571, 0.85923509,
       0.45363933, 0.93013974, 0.21762446, 0.0860678 , 0.09031691,
       0.7089933 , 0.67696929, 0.287078  , 0.85989632, 0.18982439,
       0.27075356, 0.01399549, 0.20877953, 0.8111918 , 0.28997596,
       0.20877953, 0.06850778, 0.92894082, 0.47915186, 0.63918

In [ ]:
#Save Model

In [55]:
import pickle

In [56]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)